### ISSUE TITLE
ProjectCycleException

### ISSUE THREAD

**Issue by VickF** [nokia/Avro-Schema-Generator#2]
This tools would do exactly what we need for a project at work, if I could get it running.  I built it successfully, but when attempting to run "mvn schemagen:generate", I get this error:

[ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='com.nokia.util.avro:schemagen-plugin:0.4-SNAPSHOT'}' and 'Vertex{label='com.nokia.util.avro:schemagen-core:0.4-SNAPSHOT'}' introduces to cycle in the graph com.nokia.util.avro:schemagen-core:0.4-SNAPSHOT --> com.nokia.util.avro:schemagen-plugin:0.4-SNAPSHOT --> com.nokia.util.avro:schemagen-core:0.4-SNAPSHOT -> [Help 1]
org.apache.maven.ProjectCycleException: The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='com.nokia.util.avro:schemagen-plugin:0.4-SNAPSHOT'}' and 'Vertex{label='com.nokia.util.avro:schemagen-core:0.4-SNAPSHOT'}' introduces to cycle in the graph com.nokia.util.avro:schemagen-core:0.4-SNAPSHOT --> com.nokia.util.avro:schemagen-plugin:0.4-SNAPSHOT --> com.nokia.util.avro:schemagen-core:0.4-SNAPSHOT
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:300)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)

It's odd because, as far as I can tell, there is no dependency from schemagen-core to schemagen-plugin in the code or on the pom.xml files.   

Here is my pom.xml:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"

> ```
> <modelVersion>4.0.0</modelVersion>
> ```

```
<groupId>com.nokia.util.avro</groupId>
<artifactId>schemagen</artifactId>
<name>Schemagen Parent</name>
<url>http://dchitsscm01:5000/avro-utils/summary</url>

<packaging>pom</packaging>
<version>0.4-SNAPSHOT</version>

<developers>
    <developer>
        <name>Ben Fagin</name>
        <organization>Nokia</organization>
        <email>ben.fagin@nokia.com</email>
    </developer>
</developers>

<licenses>
    <license>
        <name>ASL 2.0</name>
        <url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
        <comments>This project is licensed under ASL 2.0.</comments>
    </license>
</licenses>

<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>

<modules>
    <module>schemagen-core</module> 
    <module>schemagen-plugin</module>
</modules>

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>2.4</version>
            <configuration>
                <source>1.6</source>
                <target>1.6</target>
            </configuration>
        </plugin>

        <plugin>
            <groupId>com.nokia.util.avro</groupId>
            <artifactId>schemagen-plugin</artifactId>
            <version>0.4-SNAPSHOT</version>
            <configuration>
                <outputDirectory>
                    C:\eclipse-workspace\Avro-Schema-Generator-master\SchemaCompiler\target
                </outputDirectory>
                <packageName>mypackage</packageName>
                <schemaFiles>
                    <file>
                        C:\eclipse-workspace\Avro-Schema-Generator-master\SchemaCompiler\mySchema.xsd
                    </file>
                </schemaFiles>
            </configuration>
        </plugin>
    </plugins>


</build>

<dependencies>

    <!--test dependencies -->

    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.8.1</version>
        <scope>test</scope>
    </dependency>
</dependencies>
```

</project>

Any suggestion would be appreciated.    

Thanks,
Vick

**Comment by UnquietCode** [comment]
Hi there. It looks like you've copied the schemagen project' s pom file. This is only used for building the plugin. To use the plugin you'll need to incorporate it into your own project. Something like this:

``` xml
<groupId>your.group</groupId>
<artifactId>your.project</artifactId>

<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>

<build>
    <plugins>
        <plugin>
            <groupId>com.nokia.util.avro</groupId>
            <artifactId>schemagen-plugin</artifactId>
            <version>0.4-SNAPSHOT</version>
            <configuration>
                <outputDirectory>
                    C:\eclipse-workspace\Avro-Schema-Generator-master\SchemaCompiler\target
                </outputDirectory>
                <packageName>mypackage</packageName>
                <schemaFiles>
                    <file>
                        C:\eclipse-workspace\Avro-Schema-Generator-master\SchemaCompiler\mySchema.xsd
                    </file>
                </schemaFiles>
            </configuration>
        </plugin>
    </plugins>
</build>
```

There is also an example [available in the repository](https://github.com/Nokia/Avro-Schema-Generator/blob/master/SchemaCompiler/schemagen-plugin/src/test/resources/pom.xml).

**Comment by VickF** [comment]
Thanks!  Clearly, I’m a maven neophyte.  Your suggestion worked  first try.  I’m creating a different issue next, based on the result.

Vick
